packages:
  - apps/api
  - apps/web

verifyDepsBeforeRun: warn

overrides:
  sharp: 0.35.3
  zod: 3.25.76

allowBuilds:
  bcrypt: true
  esbuild: true
  msw: false
  sharp: true
  sqlite3: true
  workerd: true
